# Generated by Django 2.2.3 on 2019-07-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.TextField()),
                ('Lastname', models.TextField()),
                ('Center', models.TextField()),
            ],
        ),
    ]
