# Generated by Django 2.2.3 on 2019-07-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190717_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='center',
        ),
        migrations.AddField(
            model_name='profiles',
            name='region',
            field=models.TextField(default='Tema'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='firstname',
            field=models.CharField(max_length=120),
        ),
    ]
