# Generated by Django 2.2.3 on 2019-07-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190723_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='imagefile',
            field=models.FileField(default='null', upload_to='images/, null=True,verbose_name=""'),
        ),
    ]
