# Generated by Django 2.2.3 on 2019-07-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20190727_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='imagefile',
            field=models.FileField(null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
