# Generated by Django 2.2.3 on 2019-07-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20190727_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='imagefile',
            field=models.FileField(null=True, upload_to='media/', verbose_name='Image'),
        ),
    ]
