# Generated by Django 2.2.3 on 2019-07-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20190727_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='imagefile',
        ),
    ]
