# Generated by Django 2.2.3 on 2019-07-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_profiles_imagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='imagefile',
            field=models.FileField(null=True, upload_to='IMAGES', verbose_name='Image'),
        ),
    ]
